// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getFeedInfo.sql

package database

import (
	"context"
)

const getFeedInfo = `-- name: GetFeedInfo :one
SELECT id, created_at, updated_at, name, url, user_id from feeds
WHERE id = $1
`

func (q *Queries) GetFeedInfo(ctx context.Context, id int32) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedInfo, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
