// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getFeedInfo.sql

package database

import (
	"context"
)

const getFeedID = `-- name: GetFeedID :one

SELECT id from feeds
WHERE url = $1
`

func (q *Queries) GetFeedID(ctx context.Context, url string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getFeedID, url)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getFeedInfo = `-- name: GetFeedInfo :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at from feeds
WHERE id = $1
`

func (q *Queries) GetFeedInfo(ctx context.Context, id int32) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedInfo, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
