// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getUserByID.sql

package database

import (
	"context"
)

const getUserNameFromID = `-- name: GetUserNameFromID :one
SELECT name FROM users
WHERE id = $1
`

func (q *Queries) GetUserNameFromID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserNameFromID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
